### ISSUE TITLE
Admin - add title and meta-data to an Asset

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#3]
As an Admin, I want to be able to add a title and meta-data to an Asset, so that I can store information about a file.

#### Meta-data checklist:

- [x] name
- [x] parent
- [x] file
- [x] link to file if not stored on S3
- [x] creation date
- [x] file type
- [x] tags (maximum of 5)
- [x] location (maximum of 3)
- [x] uploaded_by
- [x] uploaded_at
- [x] last_edit_by
- [x] last_edit_at
- [x] owner
- [x] description
- [x] duration
- [x] collections
- [x] contributors
- [x] copyright info
- [x] enabled

##### Additionally, for Case Studies
- [x] Status
